### ISSUE TITLE
Release version 0.1.6 on github in order to be available for bower

### ISSUE THREAD

**Issue by alberskib** [darul75/ng-prettyjson#12]
Currently on github last release is **0.1.3** which does not offer editing mode (*code commented*). As a result if you use this lib as bower dependency you are able only to download 0.1.3 which in fact limit functionality. On the other hand in npm repository there is newer release (**0.1.6**). 

It will be great if this version will be also released on github (for **bower**)

[stackoverflow question](http://stackoverflow.com/questions/28211931/why-npm-has-newer-version-of-packages-than-bower)

**Comment by darul75** [comment]
thank you alberskib, new version is released and stackoverflow comment updated
