### ISSUE TITLE
Component does not resize after loading new json in parent scope

### ISSUE THREAD

**Issue by alberskib** [darul75/ng-prettyjson#14]
Steps to reproduce:
1. Enter page where directive is used with option for edition available
2. Click on edit button
3. Click on cancel button
4. In parent scope change value of the object passed to the directive - to the longer or shorter.

As a result view of editor does not resize to conform to the new content. It is not problematic if you load shorter json. In case of longer one it results in situation in which you cannot see whole value.

**Comment by alberskib** [comment]
@darul75 
At evening I will prepare PR which you can review afterwards.

**Comment by darul75** [comment]
Yes it will be great I knew some issues were still there for edition so I appreciate you collaboration and work
