### ISSUE TITLE
json displayed as a single line

### ISSUE THREAD

**Issue by germanger** [darul75/ng-prettyjson#16]
In your demo, using:

       <pre pretty-json="someJson" />

Will display the json in a multiline fashion, eg:

         {
             "bla": "blah",
             "narf": "troz"
         }

but I'm getting the json displayed in a single line, eg:

       { "bla": "blah", "narf": "troz" }

Am I missing an option?

**Comment by germanger** [comment]
maybe its a css problem?

I was checking `src/ng-prettyjson.css` and my first thought was that the class names are too general and might be colliding with other libraries. In fact theres a selector for the entire tag `pre` and maybe bootstrap.ui might have its own style for pre

    pre {outline: 1px solid #e9e9e9; padding: 5px; margin: 5px; width: 100%; height:100%;}
    .string { color: green; }
    .number { color: darkorange; }
    .boolean { color: blue; }
    .null { color: magenta; }
    .key { color: red; }
    .sep { color: black; }

**Comment by darul75** [comment]
yes it could be the cause and nice catch, I will change it soon
